# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Search-TheITJobBoard
version:      0.01
version_from: lib/WWW/Search/TheITJobBoard.pm
installdirs:  site
requires:
    HTML::TokeParser:              0.1
    WWW::Search:                   0.1
    WWW::SearchResult:             0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
